# PRACTICE PROBLEMS ON FUNCTION


**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**
**<font color='red'>[Solve all the tasks sequentially]</font>**


### Task 1
Write a function called **check_awesomeness** that takes a number as an argument and Checks whether the number is Awesome or not. If the number is Awesome, it returns True. Otherwise False.
 
**Awesome number:** a number where every digit is less than its immediate left digit is called an Awesome number. A single digit number cannot be a awesome number(e.g. 5421 is an Awesome number).

==========================================================

**Function Call1:**\
check_awesomeness(976321)\
**Output1:**\
True

==========================================================

**Function Call2:**\
check_awesomeness(9766321)\
**Output2:**\
False

==========================================================

**Function Call3:**\
check_awesomeness(9)\
**Output3:**\
False

==========================================================

**Function Call4:**\
check_awesomeness(78)\
**Output4:**\
False

==========================================================

**Function Call5:**\
check_awesomeness(87)\
**Output4:**\
True

In [1]:
#todo
#using user input
def check_awesomeness(num):
    result= True
    num_1= (str(num))[1:]
    prev_num= int(str(num)[0])
    for i in num_1:
        if len(str(num))>1:
            if int(i)<prev_num:
                prev_num= int(i)
            else:
                result= False
                break
        else:
            result= False
    return result        
       
num= int(input())
print(check_awesomeness(num))

87
True


### Task 2
Write a function called **check_awesome** that takes a list of numbers(integer) as an argument and Prints whether the number is Awesome or not.

**<font color='red'>Must reuse the check_awesomeness() function.</font>**

==========================================================

**Function Call1:**\
check_awesome([976321, 321, 9763221, 9742, 876, 3211])\
**Output1:**\
976321 is an awesome number.\
321 is a awesome number.\
9763221 is a not-so-awesome number.\
9742 is an awesome number.\
876 is an awesome number.\
3211 is a not-so-awesome number.

==========================================================

**Function Call2:**\
check_awesome([97821, 97210, 979210])\
**Output2:**\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.

In [15]:
#todo
def check_awesome(list_1):
    for i in list_1:
        def check_awesomeness(i):
            i_1= (str(i))[1:]
            num= int(str(i)[0])
            for j in i_1:
                if len(str(i))>1:
                    if int(j)<num:
                        num= int(j)
                    else:
                        return (f"{i} is a not-so-awesome number.")
                else:
                    return (f"{i} is a not-so-awesome number.")
            return (f"{i} is an awesome number.")
        print(check_awesomeness(i))
check_awesome([976321, 321, 9763221, 9742, 876, 3211])        

976321 is an awesome number.
321 is an awesome number.
9763221 is a not-so-awesome number.
9742 is an awesome number.
876 is an awesome number.
3211 is a not-so-awesome number.


### Task 3
Write a function called **find_max_min** that takes a list of numbers(integers) as a  function parameter and finds the numbers with maximum and minimum value. Then returns these two numbers as a **tuple** and prints the results using tuple unpacking in the function call accorrding to the given format. Both valid and invalid numbers should be considered for finding maximum and minimum.<font color='red'>[Must use tuple packing & unpacking] </font> 

==========================================================

**Function Call1:**\
find_max_min([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])\
**Output1:**\
Returned value from find_max_min() is: (9763221, 321)\
Number with maximum value is 9763221\
Number with minimum value is 321

==========================================================

**Function Call2:**\
find_max_min([97821, 1, 97210, 963, 979210, 979210])\
**Output2:**\
Returned value from find_max_min() is: (979210, 1)\
Number with maximum value is 979210\
Number with minimum value is 1

In [18]:
#todo
def find_max_min(list_1):
    max= list_1[0]
    min= list_1[0]
    
    for i in list_1:
        if i>max:
            max= i
        if i<min:
            min= i
    return max, min

max, min= find_max_min([97821, 1, 97210, 963, 979210, 979210])   
print("Returned value from find_max_min() is:", find_max_min([97821, 1, 97210, 963, 979210, 979210])) 
print("Number with maximum value is", max)
print("Number with minimum value is", min)

Returned value from find_max_min() is: (979210, 1)
Number with maximum value is 979210
Number with minimum value is 1


### Task 4
Write a function called **data_cleaning** that takes a string as an argument. Then gets the numbers from the given string and removes all extra spaces. Stores the clean numbers (integers) in a list and **returns** it to the function call.

==========================================================

**Function Call1:**\
data_cleaning("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")\
**Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]

==========================================================

**Function Call2:**\
data_cleaning("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")\
**Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]

==========================================================

**Function Call3:**\
data_cleaning("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")\
**Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]

In [27]:
#todo
#using built-in function
# def data_cleaning(str_1):
#     list_1= str_1.replace(" ", "").split(",")
#     list_2= []
#     for i in list_1:
#         list_2.append(int(i))
#     return list_2
# print("Data after cleaning:", data_cleaning("97821, 1     , 97210,   963,    979210 , 979210 "))


def data_cleaning(str_1):
    str_2= ""
    list_1= []
    for i in str_1:
        if i!= " ":
            if i!= ",":
                str_2+= i
            else:
                list_1.append(int(str_2))
                str_2= ""
    return list_1
print("Data after cleaning:", data_cleaning("97821, 1     , 97210,   963,    979210 , 979210 "))

Data after cleaning: [97821, 1, 97210, 963, 979210]


### Task 5
Write a function called **grouping_data** that takes  a list of numbers(integers) as a  function parameter and creates a dictionary where "valid", "invalid", and "duplicate" are the keys. The numbers that falls in those categories are the values.

**Valid & Invalid numbers:** A number with a minimum length of 4 and a maximum length of 6 is considered to be valid for this assignment. All the other numbers are considered to be Invalid numbers.\
**Duplicate numbers:** If a number appears more than once in the string, then that is a dupliacte number. Both valid and invalid numbers can be duplicates.

Lastly, print the dictionary **inside the function** and **return** the dictionary to the function call.

==========================================================

**Function Call1:**\
grouping_data([97821, 1, 97210, 963, 979210, 979210])\
**Output1:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]


==========================================================

**Function Call2:**\
grouping_data([976321, 321, 9763221, 9742, 876, 3211])\
**Output2:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]


==========================================================

**Function Call3:**\
grouping_data([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])\
**Output3:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]



In [60]:
#todo
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
def grouping_data(list_1):
    dict_1= {"valid": [], "invalid": [], "duplicate": []}
    for i in list_1:
        if i in dict_1["valid"] or i in dict_1["invalid"]:
            if i not in dict_1["duplicate"]:
                dict_1["duplicate"].append(i)
        if len(str(i))<4 or len(str(i))>6:
            dict_1["invalid"].append(i)
        if 4<=len(str(i))<=6:
            dict_1["valid"].append(i)
    print("Data dictionary printing inside the function:\n", dict_1, "\n" 
          "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", sep= "")        
    return dict_1, dict_1["valid"]

dict_1, dict_1["valid"]= grouping_data([97821, 1, 97210, 963, 979210, 979210])
print("Returned dictionary:", dict_1)
print("Valid number list obtained from the dictionary:", dict_1["valid"])

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [97821, 97210, 979210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Returned dictionary: {'valid': [97821, 97210, 979210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}
Valid number list obtained from the dictionary: [97821, 97210, 979210, 979210]


### Task6
Write a function called **individual_line_data** that takes a string as an argument. This function should do the following. 
* clean and prints the data.
* group the numbers in a dictionary obtained from the given string.
* check whether the **valid numbers** are awesome or not.
* find and print the maximum and minimum number among the **valid numbers** obtained from the given string.

*Hints:*\
You MUST reuse data_cleaning(), grouping_data(), check_awesome() and find_max_min() functions. 

==========================================================

**Function Call1:**\
individual_line_data("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")\
**Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (979210, 97210)\
Valid number with maximum value is 979210\
Valid number with minimum value is 97210




**Function Call2:**\
individual_line_data("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")\
**Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211



**Function Call3:**\
individual_line_data("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")\
**Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211


In [65]:
#todo
def individual_line_data(str_1):
    def data_cleaning(str_1):
        str_2= ""
        list_1= []
        for i in str_1:
            if i!= " ":
                if i!= ",":
                    str_2+= i
                else:
                    list_1.append(int(str_2))
                    str_2= ""
        return list_1
    print("Data after cleaning: ", data_cleaning("97821, 1     , 97210,   963,    979210 , 979210 "),
         "\n" "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", sep= "")
    
    
    def grouping_data():
        list_1= data_cleaning(str_1)
        dict_1= {"valid": [], "invalid": [], "duplicate": []}
        for i in list_1:
            if i in dict_1["valid"] or i in dict_1["invalid"]:
                if i not in dict_1["duplicate"]:
                    dict_1["duplicate"].append(i)
            if len(str(i))<4 or len(str(i))>6:
                dict_1["invalid"].append(i)
            if 4<=len(str(i))<=6:
                dict_1["valid"].append(i)   
        print("Data dictionary printing inside the function:\n", dict_1, "\n"
              "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", sep= "")        
        return dict_1, dict_1["valid"]

    dict_1, dict_1["valid"]= grouping_data()
    print("Returned dictionary:", dict_1)
    print("Valid number list obtained from the dictionary: ", dict_1["valid"], "\n"
         "=================================================", sep= "")       
    
    print("^^ Awesomeness checking of the Valid numbers ^^")
    def check_awesome():
        list_1= data_cleaning(str_1) 
        for i in list_1:
            def check_awesomeness(i):
                i_1= (str(i))[1:]
                num= int(str(i)[0])
                for j in i_1:
                    if len(str(i))>1:
                        if int(j)<num:
                            num= int(j)
                        else:
                            return (f"{i} is a not-so-awesome number.")
                    else:
                        return (f"{i} is a not-so-awesome number.")
                return (f"{i} is an awesome number.")
            print(check_awesomeness(i))
    check_awesome()    
    print("=================================================")
    def find_max_min():
        list_1= data_cleaning(str_1) 
        max= list_1[0]
        min= list_1[0]

        for i in list_1:
            if i>max:
                max= i
            if i<min:
                min= i
        return max, min

    max, min= find_max_min()   
    print("Returned value from find_max_min() is:", find_max_min()) 
    print("Number with maximum value is", max)
    print("Number with minimum value is", min)    
       
individual_line_data("976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742")

Data after cleaning: [97821, 1, 97210, 963, 979210]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [976321, 9742, 3211, 976321], 'invalid': [321, 9763221, 876], 'duplicate': [976321]}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Returned dictionary: {'valid': [976321, 9742, 3211, 976321], 'invalid': [321, 9763221, 876], 'duplicate': [976321]}
Valid number list obtained from the dictionary: [976321, 9742, 3211, 976321]
^^ Awesomeness checking of the Valid numbers ^^
976321 is an awesome number.
321 is an awesome number.
9763221 is a not-so-awesome number.
9742 is an awesome number.
876 is an awesome number.
3211 is a not-so-awesome number.
976321 is an awesome number.
Returned value from find_max_min() is: (9763221, 321)
Number with maximum value is 9763221
Number with minimum value is 321


### Task 7
Write a function called **number_analysis** that takes a list of strings as an argument and 
analyse those strings. \
**<font color='red'>Must reuse the individual_line_data() function.</font>**

In [ ]:
#todo
#No sample input, output

### Task 8
Run the following block of code for seeing the final output of this Problem.

**Output:**
######### Printing data for line no: 01 #########\
Data after cleaning: [321, 976322]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976322], 'invalid': [321], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976322], 'invalid': [321], 'duplicate': []}\
Valid number list obtained from the dictionary: [976322]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976322 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976322, 976322)\
Valid number with maximum value is 976322\
Valid number with minimum value is 976322

&emsp; 

######### Printing data for line no: 02 #########\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (979210, 97210)\
Valid number with maximum value is 979210\
Valid number with minimum value is 97210

&emsp; 

######### Printing data for line no: 03 #########\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211

&emsp;

######### Printing data for line no: 04 #########\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211

In [ ]:
# Where is sample input???